
include ../config.mk

# == Config
TARGETS := init hello test
# ==

# == Tools
LD := $(ARCH)-someos-gcc
CC := $(ARCH)-someos-gcc
#==

# == Flags
CCFLAGS += -I$(SYSROOT_DIR)/include
# ==

include ../build.mk

